{{- if .Values.isGKE -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "keep.fullname" . }}-backend-backendconfig
  namespace: {{ .Release.Namespace }}
spec:
  healthCheck:
    checkIntervalSec: {{ .Values.frontend.backendConfig.healthCheck.checkIntervalSec }}
    timeoutSec: {{ .Values.backend.backendConfig.healthCheck.timeoutSec }}
    healthyThreshold: {{ .Values.backend.backendConfig.healthCheck.healthyThreshold }}
    unhealthyThreshold: {{ .Values.backend.backendConfig.healthCheck.unhealthyThreshold }}
    requestPath: {{ .Values.backend.backendConfig.healthCheck.path }}
    port: {{ .Values.backend.backendConfig.healthCheck.port }}
    type: {{ .Values.backend.backendConfig.healthCheck.type }}
{{- end }}
