{{- if and .Values.database.enabled .Values.database.pv.enabled  -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    {{- include "keep.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
  name: {{ include "keep.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.database.pv.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.database.pv.storageClass }}
  hostPath:
    path: "/var/lib/mysql"
{{- end }}
