apiVersion: batch/v1
kind: Job
metadata:
  name: delete-keep-secrets
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    {{- include "keep.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
spec:
  template:
    spec:
      serviceAccountName: {{ include "keep.serviceAccountName" . }}
      containers:
      - name: delete-secrets-container
        image: {{ .Values.deleteSecretJob.image.repository | default "bitnami/kubectl" }}:{{ .Values.deleteSecretJob.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.deleteSecretJob.image.pullPolicy | default "Always" }}
        command:
          - /bin/sh
          - -c
          - >
            secrets=$(kubectl get secrets -n {{ include "keep.namespace" . }} -o name | grep '^secret/keep-');
            if [ -n "$secrets" ]; then
              echo "$secrets" | xargs kubectl delete -n {{ include "keep.namespace" . }};
            else
              echo "No matching secrets found to delete.";
            fi
      restartPolicy: Never
