{{- if and .Values.frontend.enabled .Values.frontend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "keep.fullname" . }}-frontend
  labels:
    {{- include "keep.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if .Values.frontend.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.frontend.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.frontend.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keep.selectorLabels" . | nindent 6 }}
      keep-component: frontend
{{- end }}
