{{- if and .Values.global.ingress.enabled (or (eq .Values.global.ingress.className "traefik") (eq .Values.global.ingress.classType "traefik")) }}
{{- $fullName := include "keep.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    {{- include "keep.labels" . | nindent 4 }}
    app.kubernetes.io/component: networking
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-strip-prefix@kubernetescrd
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/timeouts.idle: "3600s"
    traefik.ingress.kubernetes.io/timeouts.connect: "3600s"
    traefik.ingress.kubernetes.io/timeouts.read: "3600s"
    traefik.ingress.kubernetes.io/timeouts.write: "3600s"

    # WebSocket configuration
    traefik.ingress.kubernetes.io/websockets.enabled: "true"
    {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

spec:
  ingressClassName: traefik
  {{- if .Values.global.ingress.tls }}
  tls:
    {{- range .Values.global.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.global.ingress.hosts }}
    {{- range .Values.global.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- if $.Values.websocket.enabled }}
        - path: {{ $.Values.global.ingress.websocketPrefix }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-websocket
              port:
                number: {{ $.Values.websocket.service.port }}
        {{- end }}
        {{- if $.Values.backend.enabled }}
        - path: {{ $.Values.global.ingress.backendPrefix }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-backend
              port:
                number: {{ $.Values.backend.service.port }}
        {{- end }}
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-frontend
              port:
                number: {{ $.Values.frontend.service.port }}
        {{- end }}
    {{- else }}
    - http:
        paths:
        {{- if $.Values.websocket.enabled }}
        - path: {{ $.Values.global.ingress.websocketPrefix }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-websocket
              port:
                number: {{ $.Values.websocket.service.port }}
        {{- end }}
        {{- if $.Values.backend.enabled }}
        - path: {{ $.Values.global.ingress.backendPrefix }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-backend
              port:
                number: {{ $.Values.backend.service.port }}
        {{- end }}
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-frontend
              port:
                number: {{ $.Values.frontend.service.port }}
    {{- end }}
{{- end }}
