{{- if and .Values.global.ingress.enabled (or (eq .Values.global.ingress.className "haproxy") (eq .Values.global.ingress.classType "haproxy")) }}
{{- $fullName := include "keep.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    {{- include "keep.labels" . | nindent 4 }}
    app.kubernetes.io/component: networking
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    # HAProxy timeout configurations
    haproxy-ingress.github.io/timeout-client: "3600s"
    haproxy-ingress.github.io/timeout-server: "3600s"
    haproxy-ingress.github.io/timeout-connect: "3600s"
    haproxy-ingress.github.io/timeout-tunnel: "3600s"
    haproxy-ingress.github.io/ssl-redirect: "false"

    # Backend configurations for path rewrites + # WebSocket support
    haproxy-ingress.github.io/config-backend: |
      acl path_v2 path_beg {{ .Values.global.ingress.backendPrefix }}/
      acl path_ws path_beg {{ .Values.global.ingress.websocketPrefix }}/
      http-request set-path %[path,regsub(^{{ .Values.global.ingress.backendPrefix }}/,/)] if path_v2
      http-request set-path %[path,regsub(^{{ .Values.global.ingress.websocketPrefix }}/,/)] if path_ws
      timeout tunnel 3600s
      option http-keep-alive
      http-reuse safe

spec:
  ingressClassName: haproxy
  {{- if .Values.global.ingress.tls }}
  tls:
    {{- range .Values.global.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.global.ingress.hosts }}
    {{- range .Values.global.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- if $.Values.websocket.enabled }}
        - path: {{ $.Values.global.ingress.websocketPrefix }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-websocket
              port:
                number: {{ $.Values.websocket.service.port }}
        {{- end }}
        {{- if $.Values.backend.enabled }}
        - path: {{ $.Values.global.ingress.backendPrefix }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-backend
              port:
                number: {{ $.Values.backend.service.port }}
        {{- end }}
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-frontend
              port:
                number: {{ $.Values.frontend.service.port }}
        {{- end }}
    {{- else }}
    - http:
        paths:
        {{- if $.Values.websocket.enabled }}
        - path: {{ $.Values.global.ingress.websocketPrefix }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-websocket
              port:
                number: {{ $.Values.websocket.service.port }}
        {{- end }}
        {{- if $.Values.backend.enabled }}
        - path: {{ $.Values.global.ingress.backendPrefix }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-backend
              port:
                number: {{ $.Values.backend.service.port }}
        {{- end }}
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-frontend
              port:
                number: {{ $.Values.frontend.service.port }}
    {{- end }}
{{- end }}
