{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keep.fullname" . }}-redis
  labels:
    {{- include "keep.labels" . | nindent 4 }}
    keep-component: redis
spec:
  {{- if not .Values.redis.autoscaling.enabled }}
  replicas: {{ .Values.redis.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keep.selectorLabels" . | nindent 6 }}
      keep-component: redis
  template:
    metadata:
      {{- with .Values.redis.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keep.selectorLabels" . | nindent 8 }}
        keep-component: redis
    spec:
      {{- with .Values.redis.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keep.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.redis.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.redis.securityContext | nindent 12 }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
              protocol: TCP
          env:
            {{- range .Values.redis.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
          - mountPath: /data
            name: {{ include "keep.fullname" . }}-redis-pv
            readOnly: false
          {{- with .Values.redis.extraVolumeMounts }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if .Values.redis.healthCheck.enabled }}
          {{- toYaml .Values.redis.healthCheck.probes | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "keep.fullname" . }}-redis-pv
          persistentVolumeClaim:
            claimName: {{ include "keep.fullname" . }}-redis-pvc
        {{- with .Values.redis.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
