{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keep.fullname" . }}-backend
  labels:
    {{- include "keep.labels" . | nindent 4 }}
    keep-component: backend-service
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "keep.selectorLabels" . | nindent 4 }}
    keep-component: backend
{{- end }}
