apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager-role
  namespace: {{ include "keep.namespace" . }}
  labels:
    {{- include "keep.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete", "get", "list", "patch"]
