apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-rolebinding
  namespace: {{ include "keep.namespace" . }}
  labels:
    {{- include "keep.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
subjects:
  - kind: ServiceAccount
    name: {{ include "keep.serviceAccountName" . }}
    namespace: {{ include "keep.namespace" . }}
roleRef:
  kind: Role
  name: secret-manager-role
  apiGroup: rbac.authorization.k8s.io
