{{- if and .Values.websocket.enabled .Values.websocket.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "keep.fullname" . }}-websocket
  labels:
    {{- include "keep.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "keep.fullname" . }}-websocket
  minReplicas: {{ .Values.websocket.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.websocket.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.websocket.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.websocket.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.websocket.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.websocket.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
