{{- if .Values.websocket.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keep.fullname" . }}-websocket
  labels:
    {{- include "keep.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
    keep-component: websocket
spec:
  {{- if not .Values.websocket.autoscaling.enabled }}
  replicas: {{ .Values.websocket.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keep.selectorLabels" . | nindent 6 }}
      keep-component: websocket
  template:
    metadata:
      {{- with .Values.websocket.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keep.labels" . | nindent 8 }}
        app.kubernetes.io/component: websocket
        keep-component: websocket
    spec:
      {{- with .Values.websocket.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keep.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.websocket.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.websocket.securityContext | nindent 12 }}
          image: "{{ .Values.websocket.image.repository }}:{{ .Values.websocket.image.tag }}"
          imagePullPolicy: {{ .Values.websocket.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.websocket.service.port }}
              protocol: TCP
          env:
            {{- range .Values.websocket.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            - name: state-volume
              mountPath: /state
              readOnly: false
          {{- if .Values.websocket.healthCheck.enabled }}
          {{- toYaml .Values.websocket.healthCheck.probes | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.websocket.resources | nindent 12 }}
      {{- with .Values.websocket.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.websocket.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.websocket.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: state-volume
          emptyDir: {}
{{- end}}
